//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MutualFundsComparison
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MutualFundsEntities : DbContext
    {
        public MutualFundsEntities()
            : base("name=MutualFundsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FundFrame> FundFrame { get; set; }

        public System.Data.Entity.DbSet<MutualFundsComparison.Models.HomeModel> HomeModels { get; set; }
    }
}
